baseUri: http://0.0.0.0:8095/appconfig/api
isJmxEnabled: false

inject:
  enhancerFactory: org.radarbase.appconfig.inject.ManagementPortalEnhancerFactory

authentication:
  url: http://localhost:8080/managementportal/
  clientId: appconfig
  clientSecret: test
  resourceName: res_appconfig

jdbc:
  driver: "org.h2.Driver"
  url: "jdbc:h2:./data/h2"
  user:
  password:
