services:
  managementportal:
    image: radarbase/management-portal:dev
    environment:
      MANAGEMENTPORTAL_IDENTITYSERVER_SERVERURL: http://kratos:4433
      MANAGEMENTPORTAL_IDENTITYSERVER_SERVERADMINURL: http://kratos:4434
      MANAGEMENTPORTAL_IDENTITYSERVER_LOGINURL: http://127.0.0.1:8080/kratos-ui
      MANAGEMENTPORTAL_IDENTITYSERVER_ADMINEMAIL: bastiaan@thehyve.nl
      MANAGEMENTPORTAL_OAUTH_REQUIREAAL2: false
      SPRING_LIQUIBASE_CONTEXTS: dev #includes testing_data, remove for production builds
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://managementportal-postgresql:5432/managementportal
      SPRING_DATASOURCE_USERNAME: radarcns
      SPRING_DATASOURCE_PASSWORD: radarcns
      MANAGEMENTPORTAL_FRONTEND_CLIENT_SECRET: "testMe"
      MANAGEMENTPORTAL_COMMON_BASE_URL: http://localhost:8080
      MANAGEMENTPORTAL_COMMON_MANAGEMENT_PORTAL_BASE_URL: http://localhost:8080/managementportal
      MANAGEMENTPORTAL_OAUTH_CLIENTS_FILE: /mp-includes/config/oauth_client_details.csv
      MANAGEMENTPORTAL_CATALOGUE_SERVER_ENABLE_AUTO_IMPORT: 'false'
      MANAGEMENTPORTAL_OAUTH_SIGNING_KEY_ALIAS: 'radarbase-managementportal-ec'
      SERVER_SERVLET_SESSION_COOKIE_SECURE: "false"
      JAVA_OPTS: -Xmx512m  # maximum heap size for the JVM running ManagementPortal, increase this as necessary
    volumes:
      - ./etc/mp-config/:/mp-includes/config
    labels:
      - "traefik.http.routers.managementportal.rule=PathPrefix(`/managementportal`)"
      - "traefik.http.services.managementportal.loadbalancer.server.port=8080"


