version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=radarcns
      - POSTGRES_PASSWORD=radarcns
      - POSTGRES_DB=appconfig
    labels:
      - "traefik.enable=false"