# start the dockerstack using a locally built docker image of app-config.
version: "3.8"

include:
  - "../non_appconfig/docker-compose.yml"

services:
  app-config:
    extends:
      file: ../appconfig.yml
      service: app-config
    networks:
      - db
      - default

  app-config-frontend:
    extends:
      file: ../appconfig-frontend.yml
      service: app-config-frontend
    networks:
      - default
