# start the dockerstack using a locally built docker image of app-config.
include:
  - "../non_appconfig/docker-compose.yml"

services:
  app-config:
    extends:
      file: ../appconfig.yml
      service: app-config
    depends_on:
      - traefik
    networks:
      - default

  app-config-frontend:
    extends:
      file: ../appconfig-frontend.yml
      service: app-config-frontend
    depends_on:
      - traefik
    networks:
      - default
