# Continuous integration, including test and integration test
name: Publish snapshots

# Run in master and dev branches and in all pull requests to those branches
on:
  push:
    branches: [ dev ]

jobs:
  # Build and test the code
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Has SNAPSHOT version
        id: is-snapshot
        run: grep 'version = ".*-SNAPSHOT"' build.gradle.kts

      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17

      - name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Publish gradle
        uses: gradle/gradle-build-action@v2
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: -Psigning.gnupg.keyName=CBEF2CF0 -Psigning.gnupg.executable=gpg -Psigning.gnupg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} publish
