name: Snyk scheduled Docker base image scan

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

env:
    DOCKER_IMAGE_BACKEND: radarbase/radar-app-config
    DOCKER_IMAGE_FRONTEND: radarbase/radar-app-config-frontend

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Snyk to check for vulnerabilities on backend image
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.DOCKER_IMAGE_BACKEND }}
          # 'exclude-app-vulns' only tests vulnerabilities in the base image.
          # Code base vulnerabilities are tested the scheduled-snyk.yaml action.
          args: >-
            --file=radar-app-config/Dockerfile
            --fail-on=upgradable
            --severity-threshold=high
            --policy-path=.snyk
            --exclude-app-vulns
            --org=radar-base
            --sarif-file-output=snyk.sarif

      # Detected vulnerabilities will appear on Github in Security->Code_scanning_alerts tab
      - name: Upload backend result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: backend
          sarif_file: snyk.sarif

      - name: Run Snyk to check for vulnerabilities on frontend image
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.DOCKER_IMAGE_FRONTEND }}
          # 'exclude-app-vulns' only tests vulnerabilities in the base image.
          # Code base vulnerabilities are tested the scheduled-snyk.yaml action.
          args: >-
            --file=radar-app-config-frontend/Dockerfile
            --fail-on=upgradable
            --severity-threshold=high
            --policy-path=.snyk
            --exclude-app-vulns
            --org=radar-base
            --sarif-file-output=snyk.sarif

      # Detected vulnerabilities will appear on Github in Security->Code_scanning_alerts tab
      - name: Upload frontend result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: frontend
          sarif_file: snyk.sarif