name: Snyk scheduled test
on:
  schedule:
    - cron: '0 2 * * 1'
jobs:
  security:
    runs-on: ubuntu-latest
    env:
      REPORT_FILE: test.json
    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/setup@master
        with:
          snyk-version: v1.931.0

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: >
          snyk test
          --all-projects
          --configuration-matching='^runtimeClasspath$'
          --json-file-output=${{ env.REPORT_FILE }}
          --org=radar-base

      - name: Report new vulnerabilities
        uses: thehyve/report-vulnerability@master
        with:
          report-file: ${{ env.REPORT_FILE }}
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ failure() }}
